# Generated by Django 5.1.15 on 2026-09-19 13:26

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


from django.contrib.postgres.operations import BtreeGistExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(help_text='Reason/purpose for booking this campus resource.')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='approved', help_text='Booking status.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(help_text='User submitting the booking request.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(help_text='Resource requested for booking.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='resources.resource')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', django.contrib.postgres.fields.ranges.DateTimeRangeField(help_text='PostgreSQL timestamp range [start, end).')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this range slot is active for overlap enforcement.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(help_text='Associated parent booking.', on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='bookings.booking')),
                ('resource', models.ForeignKey(help_text='Target resource for range overlap enforcement.', on_delete=django.db.models.deletion.CASCADE, related_name='booking_slots', to='resources.resource')),
            ],
            options={
                'verbose_name': 'Booking Slot',
                'verbose_name_plural': 'Booking Slots',
                'ordering': ['period'],
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_active', True)), expressions=[('resource', '='), ('period', '&&')], name='prevent_overlapping_booking_slots')],
            },
        ),
    ]
