# Generated by Django 5.1.15 on 2026-09-19 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (0=Monday, 6=Sunday).')),
                ('start_time', models.TimeField(help_text='Operating start time (e.g., 08:00).')),
                ('end_time', models.TimeField(help_text='Operating end time (e.g., 20:00).')),
                ('active', models.BooleanField(default=True, help_text='Whether this availability rule is active.')),
                ('resource', models.ForeignKey(blank=True, help_text='Target resource (or null for global default operating hours).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='resources.resource')),
            ],
            options={
                'verbose_name': 'Availability Rule',
                'verbose_name_plural': 'Availability Rules',
                'ordering': ['resource', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Blackout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(help_text='Start date & time of blackout.')),
                ('end_datetime', models.DateTimeField(help_text='End date & time of blackout.')),
                ('reason', models.CharField(help_text='Reason for blackout (e.g., Maintenance, University Holiday).', max_length=255)),
                ('resource', models.ForeignKey(blank=True, help_text='Resource under blackout (or null for campus-wide blackout).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blackouts', to='resources.resource')),
            ],
            options={
                'verbose_name': 'Blackout Period',
                'verbose_name_plural': 'Blackout Periods',
                'ordering': ['-start_datetime'],
            },
        ),
    ]
