# Generated by Django 5.1.15 on 2026-09-19 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Resource category name.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Details about this resource type.')),
                ('icon', models.CharField(blank=True, default='box', help_text='Lucide icon identifier for UI.', max_length=50)),
            ],
            options={
                'verbose_name': 'Resource Type',
                'verbose_name_plural': 'Resource Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Resource name (e.g. Computer Lab 1).', max_length=150)),
                ('description', models.TextField(help_text='Detailed description of features, equipment, and rules.')),
                ('capacity', models.PositiveIntegerField(default=1, help_text='Maximum seating/user capacity.')),
                ('location', models.CharField(help_text='Physical building, floor, room number.', max_length=200)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature tags.')),
                ('image_url', models.CharField(blank=True, default='', help_text='URL or path to resource image.', max_length=500)),
                ('status', models.CharField(choices=[('available', 'Available'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved'), ('decommissioned', 'Decommissioned')], default='available', help_text='Current operational status.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custodian', models.ForeignKey(blank=True, help_text='Resource custodian in charge.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_resources', to=settings.AUTH_USER_MODEL)),
                ('resource_type', models.ForeignKey(help_text='Category of resource.', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resources.resourcetype')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['name'],
            },
        ),
    ]
